version: '3.9'
services:
  db:
    image: postgres:15
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_DB: chat_db
    ports:
      - "5433:5432"  # Alterando a porta do host para 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
